### ISSUE TITLE
Not run app

### ISSUE THREAD

**Issue by lecong** [jdachtera/rtpmidi-chrome#1]
Hi,

I install app on Chrome. But not connect to other app (at other computer). Please help me!

**Comment by jdachtera** [comment]
Hi!

The chrome sample app can only connect to a running rtpmidi server but can't create a session. The library itself can do it, but it is just not implemented in the demo app.
You can either connect to an Apple Mac OSX session or create a session using the [jdachtera/node-rtpmidi](https://github.com/jdachtera/node-rtpmidi) library (Take a look at the examples folder). Or if you want you can implement it in the demo app and make a pull request :) The api is the same as in the node library.

**Comment by lecong** [comment]
Hi!

I want create rtpmidi. How to create it. I had review jdachtera/node-rtpmidi, but do not using it.

Please help me.

**Comment by jdachtera** [comment]
Did you look at the examples? You could try examples/rtpmidi-native-bridge.js which will create a a session and a virtual midi port for you. Though this actually is a programming library and not a complete app, so you really will need to know some JavaScript to use it properly. Anyway here is a short guide:
1. Install node with npm: http://nodejs.org/download/
2. Download node-rtpmidi & install dependencies:

```
git clone https://github.com/jdachtera/node-rtpmidi.git
cd node-rtpmidi
npm install
```
1. Run the example:

```
node examples/rtpmidi-native-bridge.js
```
